In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('IRIS.csv')
print(df)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [11]:
y = df['species']
print(y)

x = df.drop(columns=['species'])
print(x)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object
     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 colum

In [12]:
x = x.to_numpy()
print(x)
y = y.to_numpy()
print(y)

print( x.shape,  y.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [15]:
# Tách dữ liệu thành tập huấn luyện và tập kiểm tra
x_train = x[:120]
y_train = y[:120]
x_test = x[120:]
y_test = y[120:]

x_train.shape, y_train.shape, x_test.shape, y_test.shape

((120, 4), (120,), (30, 4), (30,))

In [16]:

def calculate_distance(x_new, x_train):
    distances = np.sqrt(np.sum((x_new - x_train) ** 2, axis=1))
    return distances

In [ ]:
# Test thử
x_new = np.array([5.0, 3.0, 1.5, 0.3])
distances = calculate_distance(x_new, x_train)
print(f"Khoảng cách từ điểm mới đến {len(distances)} điểm train:")
print(distances[:10])

Khoảng cách từ điểm mới đến 120 điểm train:
[0.52915026 0.17320508 0.42426407 0.42426407 0.6164414  1.00995049
 0.57445626 0.41231056 0.6244998  0.24494897]


In [18]:
k = 5

# np.argsort(distances) trả về INDEX của các phần tử khi sắp xếp tăng dần
# [:k] lấy k phần tử đầu tiên (k điểm gần nhất)
top_k_indices = np.argsort(distances)[:k]

print(f"Chọn k = {k} hàng xóm gần nhất")
print(f"Index của {k} điểm gần nhất: {top_k_indices}")
print(f"Khoảng cách của {k} điểm đó: {distances[top_k_indices]}")

Chọn k = 5 hàng xóm gần nhất
Index của 5 điểm gần nhất: [25  1 45  9 34]
Khoảng cách của 5 điểm đó: [0.14142136 0.17320508 0.2236068  0.24494897 0.24494897]


In [26]:
# Lấy label của k điểm gần nhất
labels = y_train[top_k_indices]
print(f"Nhãn của {k} hàng xóm gần nhất: {labels}")

Nhãn của 3 hàng xóm gần nhất: ['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [27]:
# Bỏ phiếu
dataset_labels = np.unique(y_train)
print(f"Các loại hoa trong dataset: {dataset_labels}")

counts = {}
for label in dataset_labels:
    counts[label] = 0

for label in labels:
    counts[label] += 1

print(f"\nKết quả bỏ phiếu: {counts}")

# Chọn nhãn có số phiếu cao nhất
predicted_label = max(counts, key=counts.get)
print(f"→ Dự đoán: điểm mới thuộc loại '{predicted_label}'")

Các loại hoa trong dataset: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

Kết quả bỏ phiếu: {'Iris-setosa': 5, 'Iris-versicolor': 0, 'Iris-virginica': 0}
→ Dự đoán: điểm mới thuộc loại 'Iris-setosa'


In [28]:

# Pipeline KNN
def pipeline_knn(x_new, x_train, y_train, k):
    # Bước 1: Tính khoảng cách
    distances = calculate_distance(x_new, x_train)
    
    # Bước 2: Tìm k điểm gần nhất
    top_k_indices = np.argsort(distances)[:k]
    
    # Bước 3: Lấy nhãn của k điểm đó
    labels = y_train[top_k_indices]
    
    # Bước 4: Đếm và chọn nhãn xuất hiện nhiều nhất
    dataset_labels = np.unique(y_train)
    counts = {}
    for label in dataset_labels:
        counts[label] = 0
    
    for label in labels:
        counts[label] += 1
    
    predicted_label = max(counts, key=counts.get)
    return predicted_label

x_new = np.array([5.0, 3.0, 1.5, 0.3])
prediction = pipeline_knn(x_new, x_train, y_train, k=3)
print(f"Dự đoán cho điểm {x_new}: {prediction}")

Dự đoán cho điểm [5.  3.  1.5 0.3]: Iris-setosa


In [29]:

y_pred_test = []
k = 3

print(f"Đang dự đoán cho {len(x_test)} điểm test với k={k}...")

for i, x_test_point in enumerate(x_test):
    prediction = pipeline_knn(x_test_point, x_train, y_train, k)
    y_pred_test.append(prediction)
    
    # In tiến trình
    if (i + 1) % 10 == 0:
        print(f"Đã dự đoán {i + 1}/{len(x_test)} điểm")

y_pred_test = np.array(y_pred_test)
print(f"\n✓ Hoàn thành! Đã dự đoán xong {len(y_pred_test)} điểm")

Đang dự đoán cho 30 điểm test với k=3...
Đã dự đoán 10/30 điểm
Đã dự đoán 20/30 điểm
Đã dự đoán 30/30 điểm

✓ Hoàn thành! Đã dự đoán xong 30 điểm


In [ ]:
# Tính độ chính xác (accuracy)
correct = np.sum(y_pred_test == y_test)  # Đếm số dự đoán đúng
accuracy = correct / len(y_test) * 100

print(f"Số dự đoán đúng: {correct}/{len(y_test)}")
print(f"Độ chính xác (Accuracy): {accuracy:.2f}%")

Số dự đoán đúng: 24/30
Độ chính xác (Accuracy): 80.00%

=== Ví dụ dự đoán ===
Điểm 1: Dự đoán=Iris-virginica, Thực tế=Iris-virginica ✓ Đúng
Điểm 2: Dự đoán=Iris-virginica, Thực tế=Iris-virginica ✓ Đúng
Điểm 3: Dự đoán=Iris-virginica, Thực tế=Iris-virginica ✓ Đúng
Điểm 4: Dự đoán=Iris-versicolor, Thực tế=Iris-virginica ✗ Sai
Điểm 5: Dự đoán=Iris-virginica, Thực tế=Iris-virginica ✓ Đúng


In [31]:
print("Thử nghiệm với nhiều giá trị k khác nhau:\n")

best_k = 0
best_accuracy = 0

for k in [1, 3, 5, 7, 9, 11, 15, 21]:
    # Dự đoán với k này
    y_pred = []
    for x_test_point in x_test:
        prediction = pipeline_knn(x_test_point, x_train, y_train, k)
        y_pred.append(prediction)
    
    y_pred = np.array(y_pred)
    
    # Tính accuracy
    correct = np.sum(y_pred == y_test)
    accuracy = correct / len(y_test) * 100
    
    print(f"k={k:2d}: Accuracy = {accuracy:.2f}%")
    
    # Lưu k tốt nhất
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_k = k

print(f"\n🏆 Giá trị k tốt nhất: k={best_k} với accuracy={best_accuracy:.2f}%")

Thử nghiệm với nhiều giá trị k khác nhau:

k= 1: Accuracy = 83.33%
k= 3: Accuracy = 76.67%
k= 5: Accuracy = 80.00%
k= 7: Accuracy = 80.00%
k= 9: Accuracy = 76.67%
k=11: Accuracy = 76.67%
k=15: Accuracy = 73.33%
k=21: Accuracy = 63.33%

🏆 Giá trị k tốt nhất: k=1 với accuracy=83.33%


In [ ]:
# ============================================
# TÓM TẮT THUẬT TOÁN KNN
# ============================================
#
# KNN (K-Nearest Neighbors) - K Hàng Xóm Gần Nhất
#
# Ý tưởng: "Cho tôi biết bạn của bạn là ai, tôi sẽ nói bạn là người như thế nào"
#
# Các bước:
# 1. Tính khoảng cách từ điểm cần dự đoán đến TẤT CẢ điểm trong training set
# 2. Sắp xếp và chọn k điểm gần nhất
# 3. Lấy nhãn của k điểm đó
# 4. Bỏ phiếu: chọn nhãn xuất hiện nhiều nhất
#
# Ví dụ với k=3:
# - Điểm mới có 3 hàng xóm gần nhất: [setosa, setosa, versicolor]
# - Bỏ phiếu: setosa=2 phiếu, versicolor=1 phiếu
# - → Dự đoán: setosa (vì có 2/3 phiếu)
#
# Lưu ý:
# - k nhỏ: nhạy cảm với nhiễu, dễ overfitting
# - k lớn: mượt hơn nhưng có thể bị underfitting
# - k thường chọn lẻ để tránh hòa phiếu
#
print("✓ KNN hoàn chỉnh! Bạn đã hiểu cách KNN hoạt động rồi đấy!")