In [10]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
data = [1,2,3]

data = torch.tensor(data)
print(data)

tensor([1, 2, 3])


In [4]:
data = np.array([1,1,1])
print(data)

data = torch.from_numpy(data)
print(data)

[1 1 1]
tensor([1, 1, 1])


In [5]:
print("Random matrix")

rand_matrix = torch.rand((3,3))
print(rand_matrix)

Random matrix
tensor([[0.0937, 0.2294, 0.6993],
        [0.4098, 0.0989, 0.2588],
        [0.3350, 0.2078, 0.6850]])


In [6]:
test1 = torch.zeros((2,3))
print(test1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
test2 = torch.tensor([[1,2,3],[4,5,6]])
test2 += torch.tensor([1])

print(test2)

tensor([[2, 3, 4],
        [5, 6, 7]])


In [11]:
print("MSE sample")

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

loss = torch.mean((a - b) ** 2)
print(loss)

loss2 = nn.MSELoss()
print(loss2(a, b))

loss3 = nn.L1Loss()(a, b)
print(loss3)

MSE sample
tensor(9.)
tensor(9.)
tensor(3.)


In [12]:
data = torch.randint(low = 0, high = 10, size = (3,4))

print(data)

arg1 = torch.argmax(data, dim=0)
print(arg1)

arg2 = torch.argmax(data, dim=1)
print(arg2)

tensor([[3, 7, 6, 0],
        [3, 5, 5, 4],
        [9, 6, 8, 2]])
tensor([2, 0, 2, 1])
tensor([1, 1, 0])
